apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: training
  namespace: argocd
spec:
  description: Early Access System Training Environment
  sourceRepos:
    - git@github.com:Early-Access-Care-LLC/easv3_deployments.git
  destinations:
    - namespace: parent-training
      server: https://eaceas-q4zby22b.privatelink.eastus.azmk8s.io:443
    - namespace: child-training
      server: https://eaceas-q4zby22b.privatelink.eastus.azmk8s.io:443
    - namespace: kgateway-system
      server: https://eaceas-q4zby22b.privatelink.eastus.azmk8s.io:443
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  orphanedResources:
    warn: true
    ignore:
      - group: aquasecurity.github.io
        kind: ConfigAuditReport
        name: "*"
      - group: aquasecurity.github.io
        kind: ExposedSecretReport
        name: "*"
      - group: aquasecurity.github.io
        kind: SbomReport
        name: "*"
      - group: aquasecurity.github.io
        kind: VulnerabilityReport
        name: "*"
      - group: secrets-store.csi.x-k8s.io
        kind: SecretProviderClassPodStatus
        name: "*"
  syncWindows: []   # add “allow” windows later if you want time-based control
