apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nonprod-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:Early-Access-Care-LLC/easv3_deployments.git
    targetRevision: main
    path: argocd
    directory:
      recurse: true
      include: "{config/*.yaml,envs/dev/**/*.yaml,envs/testing/**/*.yaml,envs/staging/**/*.yaml,envs/transition/**/*.yaml,projects/dev.yaml,projects/testing.yaml,projects/staging.yaml,projects/transition.yaml}"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true        # 👈 Required
  ignoreDifferences:                         # 👇 Add this block
    - group: ""
      kind: Secret
      jsonPointers:
        - /data/tls.crt
        - /data/tls.key
      managedFieldsManagers:
        - cert-manager
