apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:Early-Access-Care-LLC/easv3_deployments.git
    targetRevision: main
    path: argocd
    directory:
      recurse: true
      include: "{config/*.yaml,envs/demo/**/*.yaml,envs/training/**/*.yaml,envs/prod/**/*.yaml,projects/demo.yaml,projects/training.yaml,projects/prod.yaml}"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
