when@dev:
    web_profiler:
        toolbar: true

    framework:
        profiler:
            enabled: true
            collect_serializer_data: true

when@test:
    framework:
        profiler: { collect: false }
