image:
  repository: earlyaccesscare/eas_v3parent_web
  tag: latest
  pullPolicy: Always

gateway:
  name: eac-gateway-prod
  sectionName: demo-parent
  enabled: true
  className: kgateway
  hosts:
    - demo.parent.v3.earlyaccesscare.com
  tls:
    secretName: parent-demo-tls
    clusterIssuer: letsencrypt-prod
  internal: false

envFrom:
  - secretRef:
      name: app-env-secret

persistentVolume:
  web:
    enabled: true
    storageClassName: azurefile-csi

service:
  web:
    type: ClusterIP
    port: 80
    
akv:
  secretProviderClass: akv-parent-demo   # override per env
