image:
  repository: earlyaccesscare/eas_v3parent_web
  tag: latest
  pullPolicy: Always

gateway:
  name: eac-gateway-nonprod
  sectionName: testing-parent
  enabled: true
  className: kgateway
  hosts:
    - testing.parent.v3.earlyaccesscare.com
  tls:
    secretName: parent-testing-tls
    clusterIssuer: letsencrypt-nonprod
  # testing uses internal ILB
  internal: true

envFrom:
  - secretRef:
      name: app-env-secret

persistentVolume:
  web:
    enabled: true
    storageClassName: azurefile-csi

akv:
  secretProviderClass: akv-parent-testing   # override per env
