image:
  repository: earlyaccesscare/eas_v3parent_web
  tag: latest
  pullPolicy: Always

gateway:
  name: eac-gateway-nonprod
  sectionName: staging-parent
  enabled: true
  className: kgateway
  hosts:
    - staging.parent.v3.earlyaccesscare.com
  tls:
    secretName: parent-staging-tls
    clusterIssuer: letsencrypt-nonprod
  # staging uses internal ILB
  internal: true

envFrom:
  - secretRef:
      name: app-env-secret

persistentVolume:
  web:
    enabled: true
    storageClassName: azurefile-csi

akv:
  secretProviderClass: akv-parent-staging   # override per env
