apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: child-training
  namespace: argocd
spec:
  project: training
  source:
    repoURL: git@github.com:Early-Access-Care-LLC/easv3_deployments.git
    targetRevision: main
    path: apps/child/helm-chart
    helm:
      valueFiles:
        - values.training.yaml   # <-- this file must live in the chart root
  destination:
    server: https://eaceas-q4zby22b.privatelink.eastus.azmk8s.io:443
    namespace: child-training
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
