apiVersion: v1
kind: Service
metadata:
  name: {{ include "eas-app-v3-child.fullname" . }}-web
  labels:
    {{- include "eas-app-v3-child.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.web.type }}
  selector:
    app: {{ include "eas-app-v3-child.name" . }}-web
  ports:
    - protocol: TCP
      port: {{ .Values.service.web.port }}
      targetPort: 80
